// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    VueTree: typeof import('./src/components/VueTree.vue')['default']
    VueTreeOne: typeof import('./src/components/VueTreeOne.vue')['default']
    VueTreeTest: typeof import('./src/components/VueTreeTest.vue')['default']
  }
}

export { }
